### ISSUE TITLE
Training and compute resources

### ISSUE THREAD

**Issue by Sahil177** [Shuijing725/CrowdNav_Prediction_AttnGraph#1]
Hi, please could you provide information about what compute resources you used to train the model and how long it took.

**Comment by Shuijing725** [comment]
We used an Intel i7-9700K CPU with 32GB memory, and an Nvidia RTX 2080 GPU. The system is any Ubuntu with version >= 16.04.
The training in the default configuration takes around 48 hours. The main bottleneck is CPU speed (clock speed, number of cores) I think.

**Comment by Sahil177** [comment]
Thank you very much, i noticed in arguments.py there is a option to increase the number of threads, do you recommend increasing this number to reduce this CPU bottleneck?

**Comment by Shuijing725** [comment]
I tried increasing `num_threads` on my computer and it makes very little difference. But I'm not entirely sure how `torch.set_num_threads()` works. Feel free to comment here if you have any idea.
