### ISSUE TITLE
Values contained in /map topic do not seem meaningful

### ISSUE THREAD

**Issue by alantes** [Shuijing725/CrowdNav_Prediction_AttnGraph#12]
Dear researcher, 

Thank you for your fantastic work. I am working on running your project. However, the messages received by /map seems not meaningful. In a map that is almost empty, the map.data I received is almost full of -1. If I understand it correctly, value 0 stands for open space without obstacles. So what is the meaning of -1 and 100:
<img width="650" alt="image" src="https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/assets/13460765/317a303b-fe77-418e-93b4-dd1b1e510690">

**Comment by Shuijing725** [comment]
What script did you run and how did you run it? I can't find /map anywhere in this repo.

**Comment by alantes** [comment]
Many apologies for my carelessness. I should have posted this question in another repo. Sorry!
