### ISSUE TITLE
part of the preprocessing module

### ISSUE THREAD

**Issue by bsxlb6** [Shuijing725/CrowdNav_Prediction_AttnGraph#15]
Excuse me，may I ask what part of the crowd preprocessing module is that?

**Comment by Shuijing725** [comment]
If you mean the robot policy network, it is in https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/main/rl/networks/selfAttn_srnn_temp_node.py

If you mean the human simulation, it is inhttps://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/main/crowd_sim/envs/crowd_sim_var_num.py

**Comment by bsxlb6** [comment]
Thank you very much for your answer

**Comment by bsxlb6** [comment]
Hi，
I have an idea. I would like to gather pedestrians who are closer and have the same direction of movement, treating them as a group. So the robot only needs to avoid this group. May I ask if this idea is feasible?If I want to modify the obstacle avoidance code of the robot to avoid crowds, where do I need to modify it?

**Comment by Shuijing725** [comment]
Yes, you can access the human velocities by `envs.humans[i].vx, envs.humans[i].vy`. Is your policy based on neural network? If no, you just need to add a new class in `https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/tree/main/crowd_nav/policy`. If yes, in addition, you also need to add the new network in `https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/tree/main/rl/networks`.
