### ISSUE TITLE
weigth for DS-RNN (original)

### ISSUE THREAD

**Issue by CAI23sbP** [Shuijing725/CrowdNav_Prediction_AttnGraph#2]
Hi @Shuijing725 !
I read your paper and code. it was awesome!!. 

Anyway, i have a single question.
I want to use your old version =DS-RNN-CrowdNav in this recently version.
In your config , there is exist about robot.policy.
So i modified this part to "srnn", and  i tested by a example weight about recently version.
Did i run original version or recently version?

**Comment by Shuijing725** [comment]
Hi @CAI23sbP,

Our provided checkpoints are all trained with the new network. You can set `robot.policy='srnn'` and train a DS-RNN policy if you want to use the old network in this new repo.

**Comment by CAI23sbP** [comment]
Thank you for your quick answer!.
