### ISSUE TITLE
GST training question.

### ISSUE THREAD

**Issue by CAI23sbP** [Shuijing725/CrowdNav_Prediction_AttnGraph#4]
Hi! @Shuijing725 , i read your reference.
But there is no script about how to make train dataset.
Could you tell me how to create dataset?
(In my situation, actually i use other platform about DRL environment. )

**Comment by LifGorg** [comment]
I have the same question as @CAI23sbP :)

**Comment by CAI23sbP** [comment]
Oh thank you for your answer @Shuijing725 !. I will try that :).
By the way, i have three questions about your code.
1. When you take a prediction data from function (generate_ob) and you calculate collision penalty in that function. why did you create like that? why did not calculate reward in reward function?
2. You created dummy human for zero detection in scan rage, i don't understand why you did.
3. This algorithm can training and testing at fixed env? It mean is you create observation space [visible_mask],[spatial_edges],[detected_human_num] are fixed size.

**Comment by Shuijing725** [comment]
Hi @CAI23sbP,

Sorry for the late reply. If you want an ORCA dataset, you can run [collect_data.py](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/main/collect_data.py). If you want real pedestrian data, then I recommend looking into Ted Huang's repo as suggested by @LifGorg.

1. To accelerate training, we calculate r_pred for multiple parallel environments in a batch manner. The true prediction reward calculation is in [this line](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/9a860be7190dc96fc9679fab073e07ce4f28e2ee/rl/vec_env/vec_pretext_normalize.py#LL153C9-L153C23).
