### ISSUE TITLE
Test result storage

### ISSUE THREAD

**Issue by Lilyoung2000** [Shuijing725/CrowdNav_Prediction_AttnGraph#6]
When I finished executing test.py, I failed to find the saved test results in the   trained_models/your_output_dir/test/  folder
Hope you can give me some advice thanks

**Comment by Shuijing725** [comment]
Hi, can you show your entire terminal output?

**Comment by Lilyoung2000** [comment]
Sorry for not getting back your info in time .
Hope you can give me some help again .Here is my terminal output

2023-08-29 16:04:28, INFO: robot FOV 2.000000
2023-08-29 16:04:28, INFO: humans FOV 2.000000
2023-08-29 16:04:28, INFO: Create other envs with new settings
trained_models/GST_predictor_rand/checkpoints/41665.pt
2023-08-29 16:04:28, INFO: human number: 20
2023-08-29 16:04:28, INFO: Randomize human's radius and preferred speed
2023-08-29 16:04:28, INFO: Circle width: 8.485281374238571
2023-08-29 16:04:28, INFO: robot FOV 6.283185
2023-08-29 16:04:28, INFO: humans FOV 6.283185
/home/ncut/anaconda3/envs/attn/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
<Monitor<CrowdSimPredRealGST<CrowdSimPredRealGST-v0>>>
No ghost version.
new gst
new st model
LOADED MODEL
device:  cuda:0


Reward=tensor([-14.4325])
Episode 0 ends in 33
Collision

Reward=tensor([-24.9099])
Episode 1 ends in 41
Collision

Reward=tensor([29.3064])
Episode 2 ends in 44
Success

Reward=tensor([36.3080])
Episode 3 ends in 49
Success

Reward=tensor([38.1377])
Episode 4 ends in 57
Success

Reward=tensor([34.4941])
Episode 5 ends in 65
Success

Reward=tensor([32.2203])
Episode 6 ends in 63
Success

Reward=tensor([27.3123])
Episode 7 ends in 49
Success
.
.
.
Reward=tensor([33.2024])
Episode 499 ends in 48
Success
2023-08-29 16:33:37, INFO: Testing success rate: 0.88, collision rate: 0.12, timeout rate: 0.00, nav time: 14.20, path length: 20.10, average intrusion ratio: 8.34%, average minimal distance during intrusions: 0.41
2023-08-29 16:33:37, INFO: Collision cases: 0 1 12 17 31 34 35 42 48 57 60 68 71 89 98 99 117 119 121 131 142 153 158 161 164 170 214 239 246 248 250 251 262 267 281 284 285 292 298 307 310 318 321 339 348 349 367 369 371 381 392 403 408 411 414 420 464 489 496 498
2023-08-29 16:33:37, INFO: Timeout cases: 
 Evaluation using 500 episodes: mean reward 27.15413

**Comment by Shuijing725** [comment]
Your terminal output is the same as what we got in our terminal and [our output files](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/main/trained_models/GST_predictor_rand/test/test_41665.pt.log). 
Are there any weird characters in your output path (like non-English characters, punctuation marks, etc)? If yes, the logs will only show in your terminal but will not be saved to file.

**Comment by Lilyoung2000** [comment]
Thanks for the quick response. I checked my output path as shown in Figure 1 below. I flipped through it, and it doesn't look like it's quite there.Is this available？
![图片](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/assets/97268825/30df70ba-d146-4fc1-a7b9-62271ff2f648)
![图片](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/assets/97268825/ebea1d54-904b-4ef2-9c26-53ebb899071f)
![图片](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/assets/97268825/ad401f3a-0905-4b87-8941-1b7393e29490)
In addition, I want to save the visualization results at the same time. What should I do?

**Comment by Shuijing725** [comment]
1. From the `test_41665.pt.log` you posted, it is saving the results normally. If you refer to the episode-level outputs (like "Reward=tensor([-14.4325]) Episode 0 ends in 33 Collision", they are not saved because they are produced by print statements. You can change the print statements to [logging operations](https://docs.python.org/3/library/logging.html) to log them.
2. To visualize, you can just change `--visualize` To `True` in [line 25, test.py](https://github.com/Shuijing725/CrowdNav_Prediction_AttnGraph/blob/9a860be7190dc96fc9679fab073e07ce4f28e2ee/test.py#L25C23-L25C34).

**Comment by Lilyoung2000** [comment]
The fact is that the test_41665.pt.log file was opened after the test ended, I don't think it is being saved. As you suggest, I should change the print statement so that I can see the episode output in the test_41665.pt.log file, right? 
Thanks to your excellent work, under your readme I know how to set up the visualization, but how to save the visualization result?

**Comment by Lilyoung2000** [comment]
Awesome, thank you for your contribution, it helps me a lot.
I hope you continue to publish many excellent papers and I wish you all the best in life
